[package]
name = "kafka-cli"
version = "0.1.0"
authors = ["Julien Senon <julien.senon@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
log = "0.4.6"
futures = "0.1.20"

[dependencies.rdkafka]
version = "~0.21"
features = ["ssl", "sasl"]